"use client";

import { useEffect, useRef, useState } from "react";

export type Locale = "da" | "en";
type Theme = "light" | "dark";
export type Project = {locale?:Locale;id:string;index:string;title:string;category:string;status:string;progress:number;accent:string;summary:string;now:string;next:string;destination:string;milestones:string[]};

const fallbackProjectData: Record<Locale, Project[]> = {
  da: [
    {id:"portfolio",index:"01",title:"Portfolio",category:"Karriere · Førsteprioritet",status:"Aktiv nu",progress:68,accent:"#f28ea2",summary:"En filmisk portfolio, der omsætter års arbejde med events, branding og kommercielle projekter til en klar professionel fortælling.",now:"Den visuelle retning og kernestrukturen er på plads. Cases som Lily / Rosie, Club Awards, Auto Awards og branchearbejde samles, mens medierne klargøres til siden.",next:"Færdiggør de stærkeste cases, skærp fortællingen om din rolle og effekt, verificér alle assets og gør oplevelsen klar til jobsøgning.",destination:"En portfolio, der gør mere end at vise arbejde: Den positionerer Patrick som det oplagte valg til roller inden for events, kreativ produktion, branding og kommercielle oplevelser.",milestones:["Positionering fastlagt","Visuelt system etableret","Cases og medier samlet","Casefortælling","Endelig QA og lancering"]},
    {id:"patrickos",index:"02",title:"PatrickOS",category:"AI-organisation · Kerneplatform",status:"Fundament bygget",progress:62,accent:"#c94779",summary:"Et genbrugeligt AI-operativsystem, der omsætter mål til koordinerede workflows med specialister, sikkerhedsgates og vedvarende kontekst.",now:"Arkitekturen, seks kerneagenter, otte workflows og eksekveringsprincipperne er på plads. Version 1.2 lukkede mission-checkpointet og Stage 6-clearance-gaten.",next:"Styrk deterministiske hooks, skill-pakning, agentisolering og distribution — og forbind derefter systemet med virkeligt arbejde som karriereudvikling og kreativ produktion.",destination:"Et produkt andre kan tage i brug: personlig kontekst ind, en koordineret AI-organisation ud — modulær, sikker og i stand til at udføre meningsfuldt arbejde med menneskelig godkendelse.",milestones:["Kernearkitektur","Agenter og workflows","Sikkerhedsgates","Hooks og modulære skills","Genbrugeligt produkt"]},
    {id:"career",index:"03",title:"Career Suite",category:"Produktkoncept · Næste lag",status:"Koncept valideret",progress:30,accent:"#ffc4bc",summary:"Et rekrutterings- og karriereopdagelseslag, der finder et menneskes reelle styrker — ikke bare matcher ord i et CV.",now:"Kerneidéerne er defineret: adaptive karriereinterviews, skjulte karriereveje, LinkedIn-optimering og rekrutteringsfokuseret positionering.",next:"Omsæt konceptet til ét fokuseret workflow i PatrickOS og test det på din egen jobsøgning før udvidelse.",destination:"Et kandidatintelligensprodukt, der kan stå alene eller blive et B2B-matchinglag for rekrutteringsfolk og jobplatforme.",milestones:["Problem identificeret","Workflow-koncept","Personlig test","Produktprototype","B2B-validering"]},
    {id:"creative",index:"04",title:"Creative Studio",category:"Kapabilitet · Senere fokus",status:"Byggesten findes",progress:24,accent:"#873467",summary:"Et udbyderuafhængigt kreativt workflow til koncepter, visuelle briefs, billedgenerering, kvalitetskontrol og publiceringsassets.",now:"Vi har udviklet gentagelige metoder gennem festivalgrafik, eventcovers, identitetsbevarelse, animationsprompts og portfolio-assets.",next:"Pak de stærkeste metoder ind i et Creative Director-workflow, når portfolioen og PatrickOS-kernen er længere fremme.",destination:"En pålidelig kreativ pipeline, der kan gå fra idé til kampagneklart output uden at være låst til én AI-udbyder.",milestones:["Eksperimenter","Promptmønstre","Kvalitetskriterier","Pakket workflow","Kreativ service"]}
  ],
  en: [
    {id:"portfolio",index:"01",title:"Portfolio",category:"Career · First priority",status:"Active now",progress:68,accent:"#f28ea2",summary:"A cinematic portfolio turning years of events, branding and commercial work into a clear professional story.",now:"The visual direction and core structure are in place. Cases such as Lily / Rosie, Club Awards, Auto Awards and industry work are being assembled while media is prepared for the site.",next:"Finish the strongest case pages, sharpen the story around your role and impact, verify every asset and make the experience application-ready.",destination:"A portfolio that does more than show work: it positions Patrick as the obvious choice for roles across events, creative production, branding and commercial experience.",milestones:["Positioning defined","Visual system established","Cases and media collected","Case storytelling","Final QA and launch"]},
    {id:"patrickos",index:"02",title:"PatrickOS",category:"AI organisation · Core platform",status:"Foundation built",progress:62,accent:"#c94779",summary:"A reusable AI operating system that turns goals into coordinated workflows with specialists, safety gates and lasting context.",now:"The architecture, six core agents, eight workflows and execution principles are in place. Version 1.2 closed the mission checkpoint and Stage 6 clearance gate.",next:"Strengthen deterministic hooks, skill packaging, agent isolation and distribution — then connect the system to real work such as career development and creative production.",destination:"A product others can adopt: personal context in, a coordinated AI organisation out — modular, safe and capable of executing meaningful work with human approval.",milestones:["Core architecture","Agents and workflows","Safety gates","Hooks and modular skills","Reusable product"]},
    {id:"career",index:"03",title:"Career Suite",category:"Product concept · Next layer",status:"Concept validated",progress:30,accent:"#ffc4bc",summary:"A recruitment and career-discovery layer that finds a person’s real strengths — not just matching words in a CV.",now:"The core ideas are defined: adaptive career interviews, hidden career paths, LinkedIn optimisation and recruiter-focused positioning.",next:"Turn the concept into one focused workflow inside PatrickOS and test it on your own job search before expanding it.",destination:"A candidate intelligence product that can stand alone or become a B2B matching layer for recruiters and job platforms.",milestones:["Problem identified","Workflow concept","Personal test","Product prototype","B2B validation"]},
    {id:"creative",index:"04",title:"Creative Studio",category:"Capability · Later focus",status:"Building blocks exist",progress:24,accent:"#873467",summary:"A provider-independent creative workflow for concepts, visual briefs, image generation, quality control and publishing assets.",now:"We have developed repeatable approaches through festival artwork, event covers, identity preservation, animation prompts and portfolio assets.",next:"Package the strongest methods into a Creative Director workflow once the portfolio and PatrickOS core are further ahead.",destination:"A reliable creative pipeline that can move from idea to campaign-ready output without being locked to one AI provider.",milestones:["Experiments","Prompt patterns","Quality criteria","Packaged workflow","Creative service"]}
  ]
};

export type Copy = {
  nav: string[]; updated: string; control: string; heroA: string; heroB: string;
  heroEm: string; intro: string; signals: [string, string][]; focus: string;
  map: string; building: string; choose: string; now: string; next: string;
  destination: string; estimate: string; method: string; process: string;
  steps: [string, string][]; long: string; door: string; motor: string;
  vision: string; visionLine: string[]; footer: string; see: string;
  sections: string; theme: string;
};

// Sidste udvej, hvis Sanity ikke svarer. Redigeres normalt i Sanity.
export const fallbackCopy: Record<Locale, Copy> = {
  da:{nav:["Projekter","Proces","Destination"],updated:"Opdateret 18.08.26",control:"PROJEKTKONTROL / 2026",heroA:"Fra løse idéer",heroB:"til et",heroEm:"system.",intro:"Et levende overblik over de vigtigste projekter, rejsen hertil og det, de tilsammen er ved at blive til.",signals:[["04","Strategiske spor"],["02","Aktive prioriteter"],["01","Fælles retning"]],focus:"Fokus er ikke at gøre alt på én gang. Fokus er at lade det vigtigste trække resten frem.",map:"01 / PROJEKTKORT",building:"Det vi bygger",choose:"Vælg et spor og se, hvor det står nu, hvad næste bevægelse er, og hvor det ender.",now:"Nu",next:"Næste bevægelse",destination:"Destination",estimate:"Fremdriftstallene er retningsgivende statusestimater — ikke falsk præcision.",method:"02 / METODEN",process:"Processen er produktet",steps:[["Opdag","Vi finder det reelle problem, styrken eller muligheden bag den første idé."],["Form","Vi gør retningen konkret gennem struktur, design og tydelige beslutninger."],["Byg","Vi omsætter det til cases, systemer og værktøjer, som virker i praksis."],["Bevis","Vi tester det på virkelige mål: jobsøgning, kreativt output og gentagelig værdi."],["Skalér","Det personlige workflow bliver til noget, andre mennesker kan bruge."]],long:"03 / LANGSIGTET RETNING",door:"Porteføljen åbner døren.",motor:"PatrickOS bygger motoren.",vision:"På sigt mødes de i én platform, der kan forstå et menneske, organisere dets ambitioner og hjælpe med at føre dem ud i verden.",visionLine:["PERSONLIGT BEVIS","GENBRUGELIGT SYSTEM","VIRKELIG EFFEKT"],footer:"Bygget af arbejdet undervejs.",see:"Se projekterne",sections:"Sidens sektioner",theme:"Skift farvetema"},
  en:{nav:["Projects","Process","Destination"],updated:"Updated 18.08.26",control:"PROJECT CONTROL / 2026",heroA:"From loose ideas",heroB:"to a",heroEm:"system.",intro:"A living overview of the most important projects, the journey so far and what they are becoming together.",signals:[["04","Strategic tracks"],["02","Active priorities"],["01","Shared direction"]],focus:"The goal is not to do everything at once. The goal is to let the most important work pull the rest forward.",map:"01 / PROJECT MAP",building:"What we are building",choose:"Choose a track to see where it stands, what comes next and where it is heading.",now:"Now",next:"Next move",destination:"Destination",estimate:"Progress figures are directional status estimates — not false precision.",method:"02 / THE METHOD",process:"The process is the product",steps:[["Discover","We find the real problem, strength or opportunity behind the first idea."],["Shape","We make the direction concrete through structure, design and clear decisions."],["Build","We turn it into cases, systems and tools that work in practice."],["Prove","We test it against real goals: applications, creative output and repeatable value."],["Scale","The personal workflow becomes something other people can use."]],long:"03 / LONG-TERM DIRECTION",door:"The portfolio opens the door.",motor:"PatrickOS builds the engine.",vision:"Over time, they meet in one platform that can understand a person, organise their ambitions and help bring them into the world.",visionLine:["PERSONAL PROOF","REUSABLE SYSTEM","REAL-WORLD IMPACT"],footer:"Built from the work in progress.",see:"See the projects",sections:"Page sections",theme:"Switch colour theme"}
};

export default function ProjectJourney({projects:serverProjects,copy:serverCopy}:{projects:Record<Locale,Project[]>;copy:Record<Locale,Copy>}){
  const[open,setOpen]=useState("portfolio");const[locale,setLocale]=useState<Locale>("da");const[theme,setTheme]=useState<Theme>("light");const heroRef=useRef<HTMLElement>(null);const t=serverCopy[locale];
  // Serveren har allerede valgt datakilde; her er den hardkodede kopi sidste udvej.
  const projects=(serverProjects[locale]?.length?serverProjects:fallbackProjectData)[locale];
  useEffect(()=>{const savedLocale=localStorage.getItem("pos-locale");const savedTheme=localStorage.getItem("pos-theme");if(savedLocale==="da"||savedLocale==="en")setLocale(savedLocale);if(savedTheme==="light"||savedTheme==="dark")setTheme(savedTheme)},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("pos-theme",theme)},[theme]);
  useEffect(()=>{document.documentElement.lang=locale;localStorage.setItem("pos-locale",locale)},[locale]);
  useEffect(()=>{const hero=heroRef.current;if(!hero)return;const move=(e:PointerEvent)=>{hero.style.setProperty("--mx",`${(e.clientX/window.innerWidth-.5)*2}`);hero.style.setProperty("--my",`${(e.clientY/window.innerHeight-.5)*2}`)};window.addEventListener("pointermove",move,{passive:true});return()=>window.removeEventListener("pointermove",move)},[]);
  return <main data-locale={locale}>
    <header className="nav"><a className="brand" href="#top" aria-label="Til toppen">P<span>—</span>OS</a><nav aria-label={t.sections}><a href="#projects">{t.nav[0]}</a><a href="#process">{t.nav[1]}</a><a href="#vision">{t.nav[2]}</a></nav><div className="nav-tools"><div className="locale-switch" aria-label="Language"><button className={locale==="da"?"active":""} onClick={()=>setLocale("da")} aria-pressed={locale==="da"}>DK</button><span>/</span><button className={locale==="en"?"active":""} onClick={()=>setLocale("en")} aria-pressed={locale==="en"}>EN</button></div><button className="theme-switch" onClick={()=>setTheme(theme==="light"?"dark":"light")} aria-label={t.theme} aria-pressed={theme==="dark"}><span>{theme==="light"?"☾":"☀"}</span></button><div className="live"><i/> {t.updated}</div></div></header>
    <section className="hero" id="top" ref={heroRef}><div className="hero-meta"><span>{t.control}</span><span>GLOSTRUP, DK</span></div><div className="hero-scene" aria-hidden="true"><div className="logo-orbit">{[0,1,2,3,4,5].map(i=><span key={i} style={{"--i":i} as React.CSSProperties}><img src="/assets/patrickos-wordmark.webp" alt=""/></span>)}</div><div className="brain-stack"><img className="brain-depth" src="/assets/patrickos-brain-clean.webp" alt=""/><img className="brain-main" src="/assets/patrickos-brain-clean.webp" alt=""/><img className="brain-shine" src="/assets/patrickos-brain-clean.webp" alt=""/></div><div className="halo halo-a"/><div className="halo halo-b"/><div className="halo halo-c"/><div className="glow"/></div><h1><span>{t.heroA}</span><br/><span>{t.heroB} <em>{t.heroEm}</em></span></h1><div className="hero-bottom"><p>{t.intro}</p><a className="circle-link" href="#projects" aria-label={t.see}>↓</a></div><div className="orbit orbit-one"/><div className="orbit orbit-two"/></section>
    <section className="signal-strip" aria-label="Key figures">{t.signals.map(([number,label])=><div key={number}><strong>{number}</strong><span>{label}</span></div>)}<p>{t.focus}</p></section>
    <section className="projects" id="projects"><div className="section-head"><span>{t.map}</span><h2>{t.building}</h2><p>{t.choose}</p></div><div className="project-list">{projects.map(project=>{const active=open===project.id;return <article className={`project ${active?"open":""}`} key={project.id} style={{"--accent":project.accent} as React.CSSProperties}><button onClick={()=>setOpen(active?"":project.id)} aria-expanded={active}><span className="project-index">{project.index}</span><span className="project-title"><small>{project.category}</small>{project.title}</span><span className="project-state"><i/>{project.status}</span><span className="project-progress"><b>{project.progress}%</b><i><u style={{width:`${project.progress}%`}}/></i></span><span className="toggle">{active?"−":"+"}</span></button><div className="project-detail"><div className="project-intro">{project.summary}</div><div className="detail-grid"><div><label>{t.now}</label><p>{project.now}</p></div><div><label>{t.next}</label><p>{project.next}</p></div><div><label>{t.destination}</label><p>{project.destination}</p></div></div><div className="milestones">{project.milestones.map((m,i)=><div className={i<Math.round(project.progress/20)?"done":""} key={m}><i/><span>{m}</span></div>)}</div></div></article>})}</div><p className="estimate">{t.estimate}</p></section>
    <section className="process" id="process"><div className="section-head light"><span>{t.method}</span><h2>{t.process}</h2></div><div className="process-flow">{t.steps.map(([title,body],i)=><div key={title}><b>0{i+1}</b><h3>{title}</h3><p>{body}</p></div>)}</div></section>
    <section className="vision" id="vision"><div className="neural-brain" aria-hidden="true"><img className="neural-base" src="/assets/patrickos-brain-clean.webp" alt=""/><img className="neural-edge neural-edge-ambient" src="/assets/patrickos-neural-edges.webp" alt=""/><img className="neural-edge neural-route neural-route-a" src="/assets/patrickos-neural-edges.webp" alt=""/><img className="neural-edge neural-route neural-route-b" src="/assets/patrickos-neural-edges.webp" alt=""/><img className="neural-edge neural-route neural-route-c" src="/assets/patrickos-neural-edges.webp" alt=""/><div className="neural-bloom"/><div className="neural-flashes"><i/><i/><i/><i/></div></div><span>{t.long}</span><p>{t.door}</p><p>{t.motor}</p><h2>{t.vision}</h2><div className="vision-line"><i/><span>{t.visionLine[0]}</span><i/><span>{t.visionLine[1]}</span><i/><span>{t.visionLine[2]}</span></div></section>
    <footer><a className="brand" href="#top">P<span>—</span>OS</a><p>{t.footer}</p><p>Patrick Bennett · 2026</p></footer>
  </main>
}
